version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: algoricca-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db/plataforma_cursos
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: algoricca-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000

  db:
    image: postgres:15-alpine
    container_name: algoricca-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: plataforma_cursos
    volumes:
      - ./bd/scripts:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
